name: Build and Publish to release branch

on:
  push:
    branches:
      - main
  workflow_dispatch:

# grant write permission so the workflow can push to the release branch using GITHUB_TOKEN
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Compute repo name (for base-href)
        id: repo
        run: echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Build Angular (production) with correct base-href
        run: |
          echo "Building for repo: $REPO_NAME"
          npm run build -- --configuration production --output-path=dist/portfolio --base-href "/"

      - name: Deploy to release branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist/portfolio/browser
          publish_branch: release
          commit_message: 'chore(publish): deploy from GitHub Actions (${GITHUB_SHA})'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: www.ranjugamage.dev
